// Autogenerated by Terraform — DO NOT EDIT MANUALLY
export const CONFIG = {
  API_GATEWAY_ENDPOINT: "${api_endpoint}",

  COGNITO_CALLBACK_ENDPOINT: "${api_endpoint}/auth/callback",

  COGNITO: {
    region: "${region}",
    userPoolId: "${user_pool_id}",
    userPoolWebClientId: "${app_client_id}",
    domain: "${cognito_domain}.auth.${region}.amazoncognito.com"
  }
};
