// Autogenerated by Terraform — DO NOT EDIT MANUALLY
export const CONFIG = {
  API_GATEWAY_ENDPOINT: "https://zfadb72vy6.execute-api.us-east-1.amazonaws.com/prod",

  COGNITO: {
    region: "us-east-1",
    userPoolId: "us-east-1_qq0M7iA2q",
    userPoolWebClientId: "u3clbt2e6igi2tb2v9v2i049v",

    domain: "factutable-auth-08dc5558.auth.us-east-1.amazoncognito.com"
  },

  COGNITO_CALLBACK_ENDPOINT: "https://zfadb72vy6.execute-api.us-east-1.amazonaws.com/prod/auth/callback"
};
