// Autogenerated by Terraform — DO NOT EDIT MANUALLY
export const CONFIG = {
  API_GATEWAY_ENDPOINT: "https://f8x51eudl3.execute-api.us-east-1.amazonaws.com",

  COGNITO_CALLBACK_ENDPOINT: "https://f8x51eudl3.execute-api.us-east-1.amazonaws.com/auth/callback",

  COGNITO: {
    region: "us-east-1",
    userPoolId: "us-east-1_GUQjvcYOi",
    userPoolWebClientId: "5h3s5vogtn74tkta9r5og30je3",
    domain: "factutable-auth-241b108d.auth.us-east-1.amazoncognito.com"
  }
};
